### ISSUE TITLE
Estuary still runs into "remote peer is missing block" issues

### ISSUE THREAD

**Issue by f8-ptrk** [application-research/estuary#90] opened 2022-01-11 00:42 UTC
```
{"level":"info","ts":"2022-01-10T18:47:08.614Z","logger":"markets","caller":"loggers/loggers.go:20","msg":"storage provider event","name":"ProviderEventDataTransferFailed","proposal CID":"bafyreifkq62sq6koo2f7z546yecc7wmbhn5jrqhia46wxxgw7nc3caqcuu","state":"StorageDealFailing","message":"error transferring data: deal data transfer failed: data transfer channel 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWBoBFLi2es6QXy485YoAnKwSoKXJYzdaMNxEVkDU6KpJh-1641552698279941539 failed to transfer data: channel 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWBoBFLi2es6QXy485YoAnKwSoKXJYzdaMNxEVkDU6KpJh-1641552698279941539: graphsync request failed to complete: remote peer is missing block: bafkreiawdgnnbjewsyy2ghqiyuopklylxoz5f7rdd6obazoejfvszcwdva"}
{"level":"warn","ts":"2022-01-10T18:47:08.614Z","logger":"providerstates","caller":"providerstates/provider_states.go:561","msg":"deal bafyreifkq62sq6koo2f7z546yecc7wmbhn5jrqhia46wxxgw7nc3caqcuu failed: error transferring data: deal data transfer failed: data transfer channel 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWBoBFLi2es6QXy485YoAnKwSoKXJYzdaMNxEVkDU6KpJh-1641552698279941539 failed to transfer data: channel 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWBoBFLi2es6QXy485YoAnKwSoKXJYzdaMNxEVkDU6KpJh-1641552698279941539: graphsync request failed to complete: remote peer is missing block: bafkreiawdgnnbjewsyy2ghqiyuopklylxoz5f7rdd6obazoejfvszcwdva"}
{"level":"info","ts":"2022-01-10T18:47:10.514Z","logger":"markets","caller":"loggers/loggers.go:20","msg":"storage provider event","name":"ProviderEventFailed","proposal CID":"bafyreifkq62sq6koo2f7z546yecc7wmbhn5jrqhia46wxxgw7nc3caqcuu","state":"StorageDealError","message":"error transferring data: deal data transfer failed: data transfer channel 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWBoBFLi2es6QXy485YoAnKwSoKXJYzdaMNxEVkDU6KpJh-1641552698279941539 failed to transfer data: channel 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWBoBFLi2es6QXy485YoAnKwSoKXJYzdaMNxEVkDU6KpJh-1641552698279941539: graphsync request failed to complete: remote peer is missing block: bafkreiawdgnnbjewsyy2ghqiyuopklylxoz5f7rdd6obazoejfvszcwdva"}
```

ping me on slack if more info is needed. If there is a better place to report this let me know

**Comment by TippyFlitsUK** [comment] 2022-01-11 08:32
I am also seeing these issues from `12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw`

`
2022-01-10T21:25:18.752Z	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventDataTransferFailed", "proposal CID": "bafyreig4gcfp3bc2enely6ru63cm7algmkzcwkaxphytaadriax2gnvehi", "state": "StorageDealFailing", "message": "error transferring data: deal data transfer failed: data transfer channel 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWBwUERBhJPtZ7hg5N3q1DesvJ67xx9RLdSaStBz9Y6Ny8-1641552698279941627 failed to transfer data: channel 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWBwUERBhJPtZ7hg5N3q1DesvJ67xx9RLdSaStBz9Y6Ny8-1641552698279941627: graphsync request failed to complete: remote peer is missing block: QmUJnUxfT5cBK6XrF8ABDQtC1yyzszfGdrvbYX15xeVeng"}
`

**Comment by gmelodie** [comment] 2022-03-19 14:05
Possible duplicate of #22

**Comment by brendalee** [comment] 2022-06-06 16:30
closing until we see this issue again

**Closed by brendalee** 2022-06-06 16:30 UTC
Labels: Bug, Duplicate
